package com.adesim.objects;

import java.awt.Color;
import java.awt.Graphics;
import java.awt.Polygon;
import java.util.ArrayList;

import utilities.xml.Xml;

import com.adesim.datastructures.SimShape;
import com.adesim.gui.PopupObjectAction;
import com.adesim.objects.model.SimModel;

public class Wall extends SimEntity {
	private static final long serialVersionUID = 1L;

	// for GUI
	public static final Color WALL_COLOR = Color.GRAY;
	public static final String TYPE = "Wall";

    public Wall(SimShape shape) {
    	super(shape, null, TYPE, true, null, WALL_COLOR);
    }

    public Wall(SimShape shape, Color color) {
    	super(shape, null, TYPE, true, color, WALL_COLOR);
    }

	@Override
	public Xml generateXML() {
		Xml wallXml = new Xml("wall");
		wallXml.addChildren(this.getShape().generateXML());
		return wallXml;
	}

	@Override
	public String getToolTipIfAny() {
		String possibleName = getNameIfNotAutoGenerated(true);
		if (possibleName == null) {
			return null; // no tooltip
		} else {
			return possibleName;
		}
	}

	@Override
	public void tick(SimModel model) {
		// do nothing.
	}

	@Override
	public ArrayList<PopupObjectAction> getPopupObjectActions() {
		return null; // no actions
	}

	@Override
	public void performAnyPostPainting(Polygon shapeOnScreen, Graphics g) {
		// do nothing
	}

	@Override
	public double defaultZLength() {
		return 2.5;
	}

} // End Wall
