/*
 * Agent Development Environment (ADE)
 *
 * @version 1.0
 * @author M@
 *
 * Copyright 1997-2013 M@ Dunlap and HRILab (hrilab.org)
 * All rights reserved. Do not copy and use without permission.
 * For questions contact M@ at <matthew.dunlap+hrilab@gmail.com>
 */
package utilities.ui.timeseries;

import ade.gui.ADEGuiCallHelper;
import ade.gui.SuperADEGuiPanel;
import java.awt.Graphics;
import java.awt.image.BufferedImage;
import org.jfree.chart.ChartFactory;
import org.jfree.chart.JFreeChart;
import org.jfree.data.time.TimeSeriesCollection;

/**
 * A simple time-series line visualization.
 *
 * I'm only using this for debugging so I've only built out what I need, if you
 * want more power don't hesitate to either add it or harass me to add it!
 *
 * @author M@ <matthew.dunlap+hrilab@gmail.com>
 */
public class TimeSeriesMonitor extends SuperADEGuiPanel {
  String title;
  BufferedImage graph = null;

  /**
   * Creates new form TimeSeriesMonitor
   */
  public TimeSeriesMonitor(ADEGuiCallHelper helper, String title) {
    super(helper, 100);
    initComponents();
    this.title = title;
    setTitle(title);
  }

  /**
   * This method is called from within the constructor to
   * initialize the form.
   * WARNING: Do NOT modify this code. The content of this method is
   * always regenerated by the Form Editor.
   */
  @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 400, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 300, Short.MAX_VALUE)
        );
    }// </editor-fold>//GEN-END:initComponents
    // Variables declaration - do not modify//GEN-BEGIN:variables
    // End of variables declaration//GEN-END:variables

  @Override
  public void refreshGui() {
    try {
      JFreeChart chart = ChartFactory.createTimeSeriesChart(title,
                                                            "Time", // time axis label
                                                            "Value", // vertical axis label
                                                            call("getData", TimeSeriesCollection.class),
                                                            true, // legend?
                                                            true, // tooltips?
                                                            true);   // urls?

      if (getWidth() > 0) {
        graph = chart.createBufferedImage(getWidth(), getHeight());
      } else {
        graph = chart.createBufferedImage(500, 500);
      }
    } catch (Exception e) {
      log.error("Oh noes!  Something went wrong while charting! ", e);
    }
    repaint();
  }

  @Override
  public void paint(Graphics g) {
    super.paint(g);
    if (graph != null) {
      g.drawImage(graph, 0, 0, null);
    }
  }
}
